export const influencerSchema = {
    table: "influencers",
    columns:
        "id, platform, platform_user_id, name, username, email, description, profile_image, profile_url, subscribers, video_count, view_count, location, createdAt, updatedAt",
    updatable: [
        "name",
        "username",
        "email",
        "description",
        "profile_image",
        "profile_url",
        "subscribers",
        "video_count",
        "view_count",
        "location",
    ],
    createTable: `CREATE TABLE IF NOT EXISTS influencers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        platform VARCHAR(50) NOT NULL,
        platform_user_id VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        username VARCHAR(255) NULL,
        email VARCHAR(255) NULL,
        description TEXT NULL,
        profile_image TEXT NULL,
        profile_url TEXT NULL,
        subscribers BIGINT NULL,
        video_count BIGINT NULL,
        view_count BIGINT NULL,
        location VARCHAR(64) NULL,
        createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_platform_user (platform, platform_user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
};
