export const influencerSchema = {
    table: "influencers",
    columns:
        "id, user_id, name, handle, platform, followers, engagement, niche, location, avatar, verified, status, notes, lastContact, createdAt, updatedAt",
    updatable: [
        "name",
        "handle",
        "platform",
        "followers",
        "engagement",
        "niche",
        "location",
        "avatar",
        "verified",
        "status",
        "notes",
        "lastContact",
    ],
    createTable: `CREATE TABLE IF NOT EXISTS influencers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        handle VARCHAR(255) NULL,
        platform VARCHAR(64) NULL,
        followers VARCHAR(64) NULL,
        engagement VARCHAR(64) NULL,
        niche VARCHAR(255) NULL,
        location VARCHAR(255) NULL,
        avatar VARCHAR(32) NULL,
        verified TINYINT(1) NOT NULL DEFAULT 0,
        status VARCHAR(64) NOT NULL DEFAULT 'saved',
        notes TEXT NULL,
        lastContact DATETIME NULL,
        createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_influencers_user (user_id),
        CONSTRAINT fk_influencers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
};
